# -*- coding: utf-8 -*-
"""testing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mWyT6nlcQLXnGoxC23tCl3DME5yL0mq2
"""

import nltk
import numpy as np
from keras.models import load_model
import pickle
from preprocessing import clean_up_sentence, bow

def load_chatbot_model(model_path='chatbot_model.h5'):
    model = load_model(model_path)
    return model

def predict_class(sentence, model, words, classes):
    p = bow(sentence, words, show_details=False)
    res = model.predict(np.array([p]))[0]

    ERROR_THRESHOLD = 0.25

    results = [[i, r] for i, r in enumerate(res) if r > ERROR_THRESHOLD]
    results.sort(key=lambda x: x[1], reverse=True)

    return_list = [{"intent": classes[r[0]], "probability": str(r[1])} for r in results]

    return return_list

def get_response(intents, tag):
    list_of_intents = intents['intents']
    for i in list_of_intents:
        if i['tag'] == tag:
            return np.random.choice(i['responses'])
    return "I'm sorry, I don't understand."

def chatbot_response(text, model, words, classes, intents):
    ints = predict_class(text, model, words, classes)
    res = get_response(intents, ints[0]['intent'])
    return res